export enum ProjectType {
  Mobile = "Mobile",
  Web = "Web",
  Work = "Work",
}

export interface ProjectData {
  project: ProjectType;

  name?: string;
  picture: string[];
  description?: string;
}

export const projects: ProjectData[] = [
  {
    project: ProjectType.Work,
    name: "RF Infinite Sdn Bhd",
    picture: [
      "./Images/Mobile/Pcari/1.png",
      "./Images/Mobile/Pcari/2.png",
      "./Images/Mobile/Pcari/3.png",
      "./Images/Mobile/Pcari/4.png",
      "./Images/Mobile/Pcari/5.png",
      "./Images/Mobile/Pcari/6.png",
      "./Images/Mobile/Pcari/7.png",
      "./Images/Mobile/Pcari/8.png",
      "./Images/Mobile/Pcari/9.png",
      "./Images/Mobile/Pcari/10.png",
      "./Images/Mobile/Pcari/11.png",
      "./Images/Mobile/Pcari/12.png",
      "./Images/Mobile/Pcari/13.png",
      "./Images/Mobile/Pcari/14.png",
      "./Images/Mobile/Pcari/15.png",
      "./Images/Mobile/Pcari/16.png",
      "./Images/Mobile/Pcari/17.png",
      "./Images/Mobile/Pcari/18.png",
      "./Images/Mobile/Pcari/19.png",
      "./Images/Mobile/Pcari/20.png",
      "./Images/Mobile/Pcari/21.png",
      "./Images/Mobile/Pcari/22.png",
      "./Images/Mobile/Pcari/23.png",
      "./Images/Mobile/Pcari/24.png",
      "./Images/Mobile/Pcari/25.png",
      "./Images/Mobile/Pcari/26.png",
      "./Images/Mobile/Pcari/27.png",
      "./Images/Mobile/Pcari/28.png",
      "./Images/Mobile/Pcari/29.png",
      "./Images/Mobile/Pcari/30.png",
      "./Images/Mobile/Pcari/31.png",
      "./Images/Mobile/Pcari/32.png",
      "./Images/Mobile/Pcari/33.png",
      "./Images/Mobile/Pcari/34.png",
      "./Images/Mobile/Pcari/35.png",
      "./Images/Mobile/Pcari/36.png",
      "./Images/Mobile/Pcari/37.png",
      "./Images/Mobile/Pcari/38.png",
      "./Images/Mobile/Pcari/39.png",
      "./Images/Mobile/Pcari/40.png",
    ],
  },
  {
    project: ProjectType.Mobile,
    name: "RF Infinite Assetsment",
    picture: [
      "./Images/Mobile/Contact/1.png",
      "./Images/Mobile/Contact/2.png",
      "./Images/Mobile/Contact/3.png",
      "./Images/Mobile/Contact/4.png",
      "./Images/Mobile/Contact/5.png",
      "./Images/Mobile/Contact/6.png",
      "./Images/Mobile/Contact/7.png",
      "./Images/Mobile/Contact/8.png",
      "./Images/Mobile/Contact/9.png",
      "./Images/Mobile/Contact/10.png",
    ],
  },
  {
    project: ProjectType.Mobile,
    name: "FYP Natural Hazard Mobile",
    picture: [
      "./Images/Mobile/natural_hazard_hub/1.png",
      "./Images/Mobile/natural_hazard_hub/2.png",
      "./Images/Mobile/natural_hazard_hub/3.png",
      "./Images/Mobile/natural_hazard_hub/4.png",
      "./Images/Mobile/natural_hazard_hub/5.png",
      "./Images/Mobile/natural_hazard_hub/6.png",
      "./Images/Mobile/natural_hazard_hub/7.png",
      "./Images/Mobile/natural_hazard_hub/8.png",
      "./Images/Mobile/natural_hazard_hub/9.png",
      "./Images/Mobile/natural_hazard_hub/10.png",
      "./Images/Mobile/natural_hazard_hub/11.png",
      "./Images/Mobile/natural_hazard_hub/12.png",
      "./Images/Mobile/natural_hazard_hub/13.png",
      "./Images/Mobile/natural_hazard_hub/14.png",
    ],
  },
  {
    project: ProjectType.Mobile,
    name: "Mosque Moments",
    picture: [
      "./Images/Mobile/MosqueMoment/1.png",
      "./Images/Mobile/MosqueMoment/2.png",
      "./Images/Mobile/MosqueMoment/3.png",
      "./Images/Mobile/MosqueMoment/4.png",
      "./Images/Mobile/MosqueMoment/5.png",
      "./Images/Mobile/MosqueMoment/6.png",
      "./Images/Mobile/MosqueMoment/7.png",
      "./Images/Mobile/MosqueMoment/8.png",
      "./Images/Mobile/MosqueMoment/9.png",
      "./Images/Mobile/MosqueMoment/10.png",
      "./Images/Mobile/MosqueMoment/11.png",
      "./Images/Mobile/MosqueMoment/12.png",
      "./Images/Mobile/MosqueMoment/13.png",
      "./Images/Mobile/MosqueMoment/14.png",
    ],
  },
  {
    project: ProjectType.Web,
    name: "FYP Natural Hazard Web",
    picture: [
      "./Images/Web/natural_hazard_hub/1.jpg",
      "./Images/Web/natural_hazard_hub/2.jpg",
      "./Images/Web/natural_hazard_hub/3.jpg",
      "./Images/Web/natural_hazard_hub/4.jpg",
      "./Images/Web/natural_hazard_hub/5.jpg",
      "./Images/Web/natural_hazard_hub/6.jpg",
    ],
  },
];
